In [25]:
import pandas as pd
import json
import os

In [26]:
data_path = 'data/Kyle_Data'
music_files = [f for f in os.listdir(data_path) if f.startswith('StreamingHistory_music') and f.endswith('.json')]

In [27]:
all_data = []

for file in music_files:
    file_path = os.path.join(data_path, file)
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        all_data.extend(data)

music = pd.DataFrame(all_data)

music = music.sort_values(by='endTime', ascending=True)

music

,endTime,artistName,trackName,msPlayed
10000,2023-11-10 00:05,David Bowie,Time - 2013 Remaster,261157
10001,2023-11-10 00:28,Unknown Artist,Unknown Track,150793
10002,2023-11-10 13:29,Steely Dan,Dirty Work,190065
10008,2023-11-10 13:42,Junior Murvin,Cool Out Son,0
10007,2023-11-10 13:42,D'Angelo,Unshaken,148053
...,...,...,...,...
21995,2024-11-10 22:02,Stan Rogers,Man with Blue Dolphin,217066
21996,2024-11-10 22:06,The Shins,Sleeping Lessons,237726
21997,2024-11-10 22:11,Daryl Hall & John Oates,I Can't Go for That (No Can Do),307306
21998,2024-11-10 22:14,The Beatles,I Saw Her Standing There - Remastered 2009,173946
21999,2024-11-10 22:33,King Gizzard & The Lizard Wizard,Sense,187120

In [28]:

most_streamed_artist_by_songs = music['artistName'].value_counts().reset_index()

most_streamed_artist_by_songs.columns = ['artistName', 'number_of_songs']

most_streamed_artist_by_songs

           artistName  number_of_songs
0         Stan Rogers             1536
1          The Smiths              904
2      Unknown Artist              756
3               Ghost              633
4         The Lemons               291
...               ...              ...
2313    Maredi Maredi                1
2314  BLESSINGS WANJA                1
2315          Humasnó                1
2316      Pete Seeger                1
2317        Metronomy                1

[2318 rows x 2 columns]

In [29]:
music['minutesPlayed'] = music['msPlayed'] / 60000

most_streamed_artist_by_minutes = music.groupby('artistName')['minutesPlayed'].sum().reset_index()
most_streamed_artist_by_minutes = most_streamed_artist_by_minutes.sort_values(by='minutesPlayed', ascending=False)

most_streamed_artist_by_minutes

         artistName  minutesPlayed
1755    Stan Rogers    4851.825000
1986     The Smiths    2527.875050
707           Ghost    2167.832667
1931    The Lemons      934.560917
440       Daft Punk     772.685700
...             ...            ...
1357    Noemi Lucas       0.001750
1687            SiR       0.001283
1653      Semisonic       0.000000
1683   Shiro SAGISU       0.000000
952   Junior Murvin       0.000000

[2318 rows x 2 columns]

In [30]:
most_played_song_by_plays = music['trackName'].value_counts().reset_index()
most_played_song_by_plays.columns = ['trackName', 'play_count']

most_played_song_by_plays

                                   trackName  play_count
0                              Unknown Track         756
1                               White Squall          80
2               The Witch of the Westmorland          68
3                         Song of the Candle          65
4                             The Jeannie C.          62
...                                      ...         ...
5101                        Forfra Forbundet           1
5102           Det´ kun vigtigt, hvad det er           1
5103                                 Nattely           1
5104  Stå Op Gå Ned (Artigeardit, Barselona)           1
5105                                   Sense           1

[5106 rows x 2 columns]

In [31]:
most_played_song_by_minutes = music.groupby('trackName')['minutesPlayed'].sum().reset_index()
most_played_song_by_minutes = most_played_song_by_minutes.sort_values(by='minutesPlayed', ascending=False)

most_played_song_by_minutes

                                    trackName  minutesPlayed
1102     Dopesmoker - 2022 Remastered Version     462.772750
4549                             White Squall     336.902367
3652                       Song of the Candle     303.466667
4092             The Witch of the Westmorland     298.520083
2492                                Mai Welly     297.716933
...                                       ...            ...
4739                                  escalon       0.000000
1947                             IGOR'S THEME       0.000000
4830  this is what falling in love feels like       0.000000
567                                   Blossom       0.000000
4024                The Importance of Stealth       0.000000

[5106 rows x 2 columns]